// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6UiAF3ErmTvZWgEWLwzezxqI9NMbcg7I',
    appId: '1:405239193729:web:454db8749ea74e1faead80',
    messagingSenderId: '405239193729',
    projectId: 'adminetic-booking-notification',
    authDomain: 'adminetic-booking-notification.firebaseapp.com',
    storageBucket: 'adminetic-booking-notification.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5yPO3z7FxTlBU5RYKQ7o6Q55hONl1tXg',
    appId: '1:405239193729:android:adf81c3fdeb7ef1eaead80',
    messagingSenderId: '405239193729',
    projectId: 'adminetic-booking-notification',
    storageBucket: 'adminetic-booking-notification.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0FhQjRonU8HrKoLcEl_OkV2j_riQa73Y',
    appId: '1:405239193729:ios:39560cdafa1fba58aead80',
    messagingSenderId: '405239193729',
    projectId: 'adminetic-booking-notification',
    storageBucket: 'adminetic-booking-notification.appspot.com',
    iosBundleId: 'com.booking.pratikshrestha404.com.np',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0FhQjRonU8HrKoLcEl_OkV2j_riQa73Y',
    appId: '1:405239193729:ios:852f8e36b7727ec1aead80',
    messagingSenderId: '405239193729',
    projectId: 'adminetic-booking-notification',
    storageBucket: 'adminetic-booking-notification.appspot.com',
    iosBundleId: 'com.example.admineticBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6UiAF3ErmTvZWgEWLwzezxqI9NMbcg7I',
    appId: '1:405239193729:web:0f58ee4f14ccad9eaead80',
    messagingSenderId: '405239193729',
    projectId: 'adminetic-booking-notification',
    authDomain: 'adminetic-booking-notification.firebaseapp.com',
    storageBucket: 'adminetic-booking-notification.appspot.com',
  );
}
